version: '3'

services:
  gradle:
    build: ./services/gradle
    volumes:
      - ./jar:/output
  selenium:
    build: ./services/selenium
    env_file:
      - ./envs/houser-sample.env
    volumes:
      - ./jar:/home/seluser/spireautomator
